### ISSUE TITLE
500 Internal server error on http access

### ISSUE THREAD

**Issue by jonigata** [ddPn08/Lsmith#1]
install and run(WSL):
```
$ git clone https://github.com/ddPn08/Lsmith.git
$ cd Lsmith
$ LD_PRELOAD="../trt/TensorRT/build/out/libnvinfer_plugin.so.8" bash launch.sh --host 0.0.0.0
```

access:
```
INFO:     127.0.0.1:42624 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:42624 - "GET /app HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:42624 - "GET /app/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/hirayama/Lsmith/dist/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path /home/hirayama/Lsmith/dist/index.html does not exist.

```

**Comment by ddPn08** [comment]
Fixed missing installation instructions in readme. You will also need to build the frontend when installing manually.
