### ISSUE TITLE
TypeError during model build

### ISSUE THREAD

**Issue by Leodmanx2** [ddPn08/Lsmith#22]
I tried to build a couple of different models, but each build fails with the same error:

```
Exporting model: models/stabilityai/stable-diffusion-2-1/onnx/unet.onnx
Downloading (…)_pytorch_model.bin";: 100%|██████████| 3.46G/3.46G [09:25<00:00, 6.13MB/s]
Downloading (…)ain/unet/config.json: 100%|██████████| 939/939 [00:00<00:00, 950kB/s]
The config attributes {'dual_cross_attention': False, 'num_class_embeds': None, 'only_cross_attention': False, 'use_linear_projection': True, 'upcast_attention': True} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 266, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 269, in wrap
    await func()
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
  File "/app/./modules/diffusion/tensorrt/engine.py", line 154, in build
    engine = build_engine(
  File "/app/./modules/diffusion/tensorrt/engine.py", line 41, in build_engine
    model = model_data.get_model()
  File "/app/./modules/diffusion/tensorrt/models.py", line 53, in get_model
    return UNet2DConditionModel.from_pretrained(
  File "/app/./submodules/diffusers_0_7_2/src/diffusers/modeling_utils.py", line 485, in from_pretrained
    model, unused_kwargs = cls.from_config(
  File "/app/./submodules/diffusers_0_7_2/src/diffusers/configuration_utils.py", line 174, in from_config
    model = cls(**init_dict)
  File "/app/./submodules/diffusers_0_7_2/src/diffusers/configuration_utils.py", line 444, in inner_init
    init(self, *args, **init_kwargs)
  File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/unet_2d_condition.py", line 135, in __init__
    down_block = get_down_block(
  File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/unet_2d_blocks.py", line 65, in get_down_block
    return CrossAttnDownBlock2D(
  File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/unet_2d_blocks.py", line 535, in __init__
    out_channels // attn_num_head_channels,
TypeError: unsupported operand type(s) for //: 'int' and 'list'
```

The models I tried, specifically, were stabilityai/stable-diffusion-2-1 and hakurei/waifu-diffusion.
I set up Lsmith using Docker on Windows 11 with a freshly installed Windows Subsystem for Linux 2 running Ubuntu 22.04.1 LTS.

**Comment by mvsw-roman** [comment]
diffusers 0.7.2 is old and was released before stable diffusiion 2.0 - 2.1 models

**Comment by Leodmanx2** [comment]
Ah, that did it. The submodule needed to be updated with `--remote`.
