### ISSUE TITLE
browser console error

### ISSUE THREAD

**Issue by jonigata** [ddPn08/Lsmith#4]
GUI page has displayed, but I get an error and can't proceed.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/128374/216824119-ecb2ab7a-e6a5-42be-8e2a-87edb584e568.png">

and server error:
```
INFO:     192.168.208.1:50078 - "GET /api/model/currnet HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hirayama/Lsmith/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/hirayama/Lsmith/./modules/api/routes/model_api.py", line 25, in get_current_runner
    return ModelCurrentResponseModel(status="success", data=runner.current.model_id)
AttributeError: 'NoneType' object has no attribute 'model_id'
INFO:     192.168.208.1:50077 - "GET /api/model/list HTTP/1.1" 200 OK
```

**Comment by ddPn08** [comment]
First you need to build the model into an engine in the "engine" tab.
Sorry for the lack of explanation.
I will add a description of the generation soon.
The error has been fixed in this commit.
https://github.com/ddPn08/Lsmith/commit/8abfe7e3e19323d41799c816a21a4a6354756645
